### ISSUE TITLE
Next and previous page links don't work

### ISSUE THREAD

**Issue by Djas2017** [algolia/demo-structured-result#4]
Hi,

The links to other pages at the bottom of the search page do not work!
Something specific to be adjusted?
 
![algolia-structured-results-next-previous-page-issue](https://user-images.githubusercontent.com/25626639/72860557-27939b00-3c95-11ea-9078-ea2cfa88f24b.png)

Thanks

**Comment by Haroenv** [comment]
We seem to have forgotten about this demo. I have made an updated version quickly here: https://codesandbox.io/s/zealous-grothendieck-tt2v9

We will update the guide on the docs following the new demo soon

**Comment by Djas2017** [comment]
Thank you!
